global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Zookeeper JMX Exporter (NEW)
  # - job_name: 'zookeeper-jmx'
  #   static_configs:
  #     - targets: ['zookeeper-jmx-exporter:5556']
  #       labels:
  #         service: 'zookeeper'
  #         env: 'production'
  #   metrics_path: /metrics
  #   scrape_interval: 10s
  #   scrape_timeout: 5s

  # ClickHouse Exporter
  - job_name: 'clickhouse-exporter'
    static_configs:
      - targets: ['clickhouse:9126']
        labels:
          service: 'clickhouse'
          env: 'production'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  # Node Exporter (for host metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'host'
          env: 'production'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  # Consumer Service
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8002']
        labels:
          env: 'local'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  # Backend Application
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
        labels:
          env: 'local'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s